# Generated by Django 5.2 on 2025-05-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('maintenance', 'Maintenance Help'), ('diy', 'DIY Repairs'), ('buying', 'Buying/Selling Advice'), ('general', 'General Discussion')], default='general', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
