# Generated by Django 5.2 on 2025-05-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_post_category_post_cat_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Reply to another reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.reply'),
        ),
    ]
