# Generated by Django 5.2 on 2025-05-02 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_reply_parent'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle related to this post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='vehicles.vehicle'),
        ),
    ]
