# Generated by Django 5.2 on 2025-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('maintenance', 'Maintenance Help'), ('diy', 'DIY Repairs'), ('buying', 'Buying/Selling Advice'), ('general', 'General Discussion'), ('marketplace', 'Marketplace')], default='general', max_length=100),
        ),
    ]
