# Generated by Django 5.2 on 2025-04-29 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(db_index=True, help_text='UK-style plate, e.g. AB12CDE.', max_length=12, unique=True, verbose_name='Registration Number')),
                ('make', models.CharField(help_text='Manufacturer, e.g. Ford, Toyota.', max_length=64, verbose_name='Make')),
                ('model', models.CharField(help_text='Model name or number, e.g. Fiesta.', max_length=64, verbose_name='Model')),
                ('year', models.PositiveIntegerField(help_text='Four-digit year, e.g. 2018.', verbose_name='Year of Manufacture')),
                ('vin', models.CharField(blank=True, help_text='17-character Vehicle Identification Number.', max_length=17, null=True, verbose_name='Vehicle VIN')),
                ('photo', models.ImageField(blank=True, help_text='Optional vehicle image.', upload_to='vehicles/photos/%Y/%m/', verbose_name='Photo')),
                ('share_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for sharing this vehicle via a link.', unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who added this vehicle.', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['owner', 'reg_number'], name='vehicles_ve_owner_i_9bb589_idx')],
            },
        ),
    ]
