# Generated by Django 5.2 on 2025-05-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='milage',
            field=models.PositiveIntegerField(blank=True, help_text='Current mileage in kilometers.', null=True, verbose_name='Mileage'),
        ),
    ]
