# Generated by Django 5.2 on 2025-05-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_milage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='milage',
            field=models.PositiveIntegerField(blank=True, help_text='Current Mileage', null=True, verbose_name='Mileage'),
        ),
    ]
