# Generated by Django 5.2 on 2025-04-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date expense occurred.')),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('repair', 'Repair'), ('ins', 'Insurance'), ('tax', 'Tax'), ('other', 'Other')], default='other', help_text='Expense category.', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in GBP (£).', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['vehicle', 'category'], name='logs_expens_vehicle_16f813_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of service.')),
                ('mileage', models.PositiveIntegerField(help_text='Odometer reading at service.')),
                ('service_type', models.CharField(choices=[('oil', 'Oil Change'), ('tyre', 'Tyre Replacement'), ('brake', 'Brake Service'), ('insp', 'Inspection'), ('other', 'Other')], default='other', help_text='Type of maintenance performed.', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['vehicle', 'date'], name='logs_mainte_vehicle_1e218d_idx')],
            },
        ),
    ]
