# Generated by Django 5.2 on 2025-05-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of service in GBP (£).', max_digits=10, null=True),
        ),
    ]
